application: golang-org
version: sandbox
runtime: custom
api_version: go1
vm: true

manual_scaling:
  instances: 5

health_check:
  check_interval_sec: 20
  restart_threshold: 10

handlers:
- url: /.*
  script: _go_app

