id: sandbox-controller
kind: ReplicationController
apiVersion: v1beta1
desiredState:
  replicas: 5
  replicaSelector:
    name: sandbox
  podTemplate:
    desiredState:
      manifest:
        version: v1beta2
        containers:
        - name: sandbox
          # TODO(proppy): publish the sandbox image to the hub
          image: golang/playground-sandbox
          ports:
          - name: sandbox-server
            containerPort: 8080
    labels:
      name: sandbox