application: go-playground
version: 1
runtime: go
api_version: go1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico
  secure: always
- url: /static
  static_dir: static
  secure: always
- url: /(|compile|fmt|share|playground.js)
  script: _go_app
  secure: always
- url: /p/.+
  script: _go_app
  secure: always
